wheel_right_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_right_joint
wheel_left_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_left_joint
joint_states_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 100