wheel_right_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_right_joint
    pid: {p: 1, i: 0, d: 0}
    wheel_left_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_left_joint
    pid: {p: 1, i: 0, d: 0}
joint_states_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 100